name: CI
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null
jobs:
  build:
    runs-on: ubuntu-latest
    parameters:
      - name: image
        values: 13
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: 'echo Hello, world!'
      - name: Run the parrameterised value
        run: 'echo this is the version ${{parameters.image}}'
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
